[package]
name = "csv-txt-excel-parallel-toolkit"
version = "0.4.14"
edition = "2021"
authors = ["zhuang dai <ribbondz@163.com>"]
description = "A parallel and fast command line toolkit for small and large (>10G) CSV, TXT, and EXCEL files, with a unified api."
license = "MIT OR Unlicense"
repository = "https://github.com/ribbondz/rsv"
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.11"
bytecount = "0.6.8"
calamine ={version = "0.26.1", features=['dates']}
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["derive"] }
crossbeam-channel = "0.5.13"
dashmap = "6.1.0"
rand = "0.8.5"
rayon = "1.10.0"
regex = "1.11.0"
tabled = "0.16.0"
xlsxwriter = "0.6.1"


[dev-dependencies]
execute = "0.2.13"

# to save typing, the binary is renamed to rsv, a combination of Rust+CSV.
[[bin]]
name = "rsv"
path = "src/main.rs"
