[package]
name = "csv-txt-excel-parallel-toolkit"
version = "0.4.5"
edition = "2021"
authors = ["zhuang dai <ribbondz@163.com>"]
description = "A parallel and fast command line toolkit for small and large (>10G) CSV, TXT, and EXCEL files, with a unified api."
license = "MIT OR Unlicense"
repository = "https://github.com/ribbondz/rsv"
categories = ["command-line-utilities", "Command-line interface"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.2"
bytecount = "0.6.3"
calamine = "0.19.1"
chrono = "0.4.23"
clap = { version = "4.0.32", features = ["derive"] }
crossbeam-channel = "0.5.6"
dashmap = "5.4.0"
execute = "0.2.11"
rayon = "1.6.1"
regex = "1.7.0"
tabled = "0.10.0"
xlsxwriter = "0.5.0"

# to save typing, the binary is renamed to rsv, a combination of Rust+CSV.
[[bin]]
name = "rsv"
path = "src/main.rs"
