[package]
name = "rsv"
version = "0.4.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.2"
bytecount = "0.6.3"
calamine = "0.19.1"
chrono = "0.4.23"
clap = { version = "4.0.32", features = ["derive"] }
crossbeam-channel = "0.5.6"
dashmap = "5.4.0"
rayon = "1.6.1"
regex = "1.7.0"
tabled = "0.10.0"
