# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - cargo build --release
      
  publish:
    cmds:
      - task build
      - task compress

  build:
    cmds:
      - cross build --release --target x86_64-pc-windows-gnu
      - cross build --release --target x86_64-pc-windows-msvc
      - cross build --release --target x86_64-unknown-linux-musl

  compress:
    dir: D:\code\rsv
    cmds:
      # - zip.exe -j dis\\x86_64-pc-windows-gnu.zip README.md target\\x86_64-pc-windows-gnu\\release\\rsv.exe
      - zip.exe -j dis\\x86_64-pc-windows-msvc.zip README.md target\\x86_64-pc-windows-msvc\\release\\rsv.exe
      # - zip.exe -j dis\\x86_64-unknown-linux-musl.zip README.md target\\x86_64-unknown-linux-musl\\release\\rsv

  compress1:
    dir: D:\code\rsv
    cmds:
      - zip.exe -j dis\\x86_64-pc-windows-msvc.zip README.md target\\release\\rsv.exe
